name: Crawl TW Company Contacts

on:
  schedule:
    - cron: '0 1 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install requests beautifulsoup4 pandas chardet phonenumbers tldextract openpyxl
      - name: Run crawler
        run: python -m src.crawler
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: csv/output/taiwan_company_contacts_*.csv
